// packages/screeb-sdk-browser-example/src/App.svelte
<script lang="ts">
	import * as Screeb from "@screeb/sdk-browser";
	import { onMount } from "svelte"
	import screebLogo from "./assets/screeb.png"

	onMount(async () => {
	  await Screeb.load()
	  // eslint-disable-next-line no-console
	  console.log("screeb loaded")
	  await Screeb.init("0e2b609a-8dce-4695-a80f-966fbfa87a88", "dev@screeb.app", {
	    authenticated: true,
	    firstname: "John",
	    last_seen_at: new Date(),
	    lastname: "Smith",
	    org_size: 20,
	  })
	
  // eslint-disable-next-line no-console
	  console.log(await Screeb.debug())

	  await Screeb.eventTrack("screeb-sdk-browser-example started", {
	    test: 123,
	  })
	  await Screeb.identityProperties({ hello: "I'm a dev." })
	  await Screeb.identityGroupAssign("cohort", "Screeb Developers")

	  setTimeout(async () => {
	    // eslint-disable-next-line no-console
	    console.log(await Screeb.identityGet())
	  }, 200)
	})
</script>

<main>
	<img src={screebLogo} alt="This is the Screeb.app logo" />
	<h1>Hello <em>you</em>!</h1>

	<h2>Welcome aboard!</h2>
	<p>
		Visit our
		<a
			href="https://github.com/ScreebApp/developers/wiki/Javascript-SDK-install"
			target="_blank"
		>
			Developer documentation
		</a>
		to learn how to integrate
		<a href="https://screeb.app" target="_blank">Screeb</a>.
	</p>
</main>

<style>
	img {
		margin-top: 1em;
		max-width: 100px;
	}

	main {
		color: #303140;
		text-align: center;
		padding: 1em;
		max-width: 240px;
		margin: 0 auto;
	}

	h1 {
		font-size: 4em;
		font-weight: 500;
		font-family: Rubik;
		margin-block-start: 0.2em;
		margin-block-end: 0.2em;
	}

	h2 {
		font-size: 1.2em;
		font-weight: 500;
		font-family: Rubik;
	}

	em {
		font-style: normal;
		color: #5e21f1;
		font-weight: 700;
	}

	a {
		font-weight: 700;
		color: #5e21f1;
	}

	@media (min-width: 640px) {
		main {
			max-width: none;
		}
	}
</style>

// packages/screeb-sdk-react-example/src/App.tsx
import { useScreeb } from "@screeb/sdk-react";
import * as React from "react";

import reactLogo from "./assets/react.svg";
import screebLogo from "./assets/screeb.png";

import "./App.css";

function App() {
  const {
    debug,
    eventTrack,
    identityProperties,
    identityGroupAssign,
    identityGet,
  } = useScreeb();

  React.useEffect(() => {
    debug();
    eventTrack("screeb-sdk-react-example started", { test: 123 });
    identityProperties({ hello: "I'm a dev." });
    identityGroupAssign("cohort", "Screeb Developers");

    // eslint-disable-next-line no-console
    setTimeout(() => identityGet().then(console.log), 500);
  }, [debug, eventTrack, identityProperties, identityGroupAssign, identityGet]);

  return (
    <main>
      <header>
        <img src={screebLogo} alt="This is the Screeb.app logo" />
        <span>+</span>
        <img src={reactLogo} alt="This is the React logo" />
      </header>
      <h1>
        Hello <em>you</em>!
      </h1>
      <h2>Welcome aboard!</h2>
      <p>
        Visit our&nbsp;
        <a
          href="https://github.com/ScreebApp/developers/wiki/Javascript-SDK-install"
          target="_blank"
        >
          Developer documentation
        </a>
        &nbsp;to learn how to integrate&nbsp;
        <a href="https://screeb.app" target="_blank">
          Screeb
        </a>
        .
      </p>
    </main>
  );
}

export default App;
